server:
    port: 8035
            
feign:
    hystrix:
        enabled: false
        
ribbon:
    ConnectTimeout: 7000
    ReadTimeout: 8000
    
security:
    basic:
        enabled: false
    oauth2:
        authorization:
            check-token-access: http://localhost:8010/auth/oauth/check_token
        client:
            clientId: 10081
            clientSecret: 123456
            grant-type: password
            scope: read
        resource:
            filter-order: 3
            
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: 123456
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/kcloud-bom?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: root
        validationQuery: SELECT 1 FROM DUAL
        
mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.kcloud.tum.model.entity 
       
mybatis-plus:
    global-config:
        db-config:
            db-type: MYSQL 
    mapper-locations: classpath:mapper/*.xml 
    
logging:
    level:
        com:
          kcloud:
            tum:
              mapper: DEBUG
